{{- /*
See ds-gcp-nvidia-installer.yaml for the GCP/GKE version (GKE does not use Garden Linux)
*/}}
{{- if .Values.targetInfrastructure.gardener }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "garden-nvidia-installer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nvidia-installer.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: {{ template "nvidia-installer.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "nvidia-installer.name" . }}
        k8s-app: {{ template "nvidia-installer.name" . }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      priorityClassName: system-node-critical
      {{- if .Values.nvidiaInstaller.nodeAffinity }}
      affinity:
        nodeAffinity:
{{ toYaml .Values.nvidiaInstaller.nodeAffinity | indent 10 }}
      {{- end}}
      hostPID: true
      imagePullSecrets:
      - name: {{ template "garden-nvidia-installer.fullname" . }}
      {{- if .Values.debug }}
      containers:
      {{- else }}
      initContainers:
      {{- end }}
      - image: {{ printf "%s/%s:%s" .Values.global.imageRepository .Values.nvidiaInstaller.installerImage (.Values.nvidiaInstaller.installerTag | default .Chart.Version) }}
        name: modulus
        imagePullPolicy: {{ ternary "Always" "IfNotPresent" .Values.debug }}
        args:
        {{- if .Values.debug }}
        - "--debug"
        {{- end }}
        securityContext:
          privileged: true
{{- if .Values.nvidiaInstaller.installerResources }}
        resources:
{{ toYaml .Values.nvidiaInstaller.installerResources | indent 12 }}
{{- end }}
        env:
        - name: LD_ROOT
          value: /root
{{- if .Values.nvidiaInstaller.environment }}
{{ toYaml .Values.nvidiaInstaller.environment | indent 8 }}
{{- end }}
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: ld-root
          mountPath: /root
        - name: module-cache
          mountPath: /opt/modulus/cache
        - name: module-install-dir-base
          mountPath: {{ required "nvidiaInstaller.hostDriverPath" .Values.nvidiaInstaller.hostDriverPath }}
{{- if .Values.nvidiaInstaller.removeTaintWhenReady }}
      # Once the driver is installed, remove the specified taint so that GPU-requesting pods can run
      - name: untaint
        image: {{ printf "%s/%s" .Values.global.imageRepository .Values.nvidiaInstaller.kubectlImage }}
        command:
          - /bin/sh
        args:
          - '-c'
          - 'kubectl taint node "${NODE}" {{.Values.nvidiaInstaller.removeTaintWhenReady}}:NoSchedule- || true'
        env:
          - name: NODE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
{{- end }}
      {{- if not .Values.debug }}
      containers:
      - image: {{ printf "%s/%s" .Values.global.imageRepository .Values.nvidiaInstaller.pauseImage }}
        name: pause
      {{- end }}
        resources:
{{ toYaml .Values.nvidiaInstaller.pauseResources | indent 12 }}
{{- if .Values.nvidiaInstaller.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nvidiaInstaller.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.nvidiaInstaller.tolerations }}
      tolerations:
{{ toYaml .Values.nvidiaInstaller.tolerations | indent 6 }}
{{- end }}
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: ld-root
        hostPath:
          path: /
      - name: module-cache
        hostPath:
          path: /opt/modulus/cache
      - name: module-install-dir-base
        hostPath:
          path: {{ required "nvidiaInstaller.hostDriverPath" .Values.nvidiaInstaller.hostDriverPath }}
{{- end }}
