{{- if .Values.nvidiaInstaller.installRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-installer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-nodes
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-nodes-to-nvidia-installer-sa
subjects:
- kind: ServiceAccount
  name: nvidia-installer
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: update-nodes
  apiGroup: rbac.authorization.k8s.io
{{- end}}