
apiVersion: v1
kind: Pod
metadata:
  name: gpu-example
  namespace: default
spec:
  containers:
    - name: gpu-debug-pod
      image: debian
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
      command: ["/bin/bash"]
      env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib
      args: ['-c', "ls -l /dev/nvidia* ; /usr/local/nvidia/bin/nvidia-smi; sleep 10000d"]
  tolerations:
   - key: "nvidia.com/gpu"
     operator: "Exists"
     effect: "NoSchedule"
   - key: "test"
     operator: "Exists"
     effect: "NoSchedule"
