version: 1.2.0-sap7
description: system pod for installing nvidia gpu drivers in the host operating system

steps:
  jenkins:
    type: jenkinsJob
    job: aicore/nvidia-installer
    params:
      ComponentName: nvidia-installer
      BuildContext: '{builtin.encoded_contexts}'
      RunStaticScans: '{RunStaticScans}'
      RunUnitTests: '{RunUnitTests}'
      Release: '{Release}'
      Build: '{Build}'
      BuildXmake: '{BuildXmake}'
      TREEISH: '{builtin.git_commit}'
      RunTests: '{RunTests}'
      RunCheckmarx: '{RunCheckmarx}'
      RunWhitesource: '{RunWhitesource}'
      RunSonarQube: '{RunSonarQube}'
      RunWhitesourceDocker: '{RunWhitesourceDocker}'
      RunPPMSComplianceForImage: '{RunPPMSComplianceForImage}'
      RunProtecode: '{RunProtecode}'
  build:
    type: dockerbuild
    artifact: image
    dockerfile: Dockerfile
    buildArgs:
      GIT_COMMIT: '{builtin.git_commit}'
      GIT_TAG: '{builtin.version}'
      GIT_TREE_STATE: '{builtin.git_tree_state}'
  whitesource:
    type: whitesource

artifacts:
  image:
    type: docker
    imageName: com.sap.ai/nvidia-installer-{kernelVersion}-{driverVersion}{image_suffix}

context:
  imageName: com.sap.ai/nvidia-installer{image_suffix}
  driverVersion: "450.80.02"
  # Do not edit kernelVersion - master value is in gardenlinux-dev/component.yaml context section.
  kernelVersion: 5.4.0-5-cloud-amd64

pipelines:
  local:
    build: build
  push-validation:
    build: jenkins
  main:
    build: jenkins
  release:
    build: jenkins

patch:
- file: .xmake.cfg
  regexp: version=.*
  replace: version={builtin.version}
- file: helm/Chart.yaml
  yaml_path: version
  replace: '{builtin.version}'
- file: helm/values.yaml
  regexp: 'driverVersion: .*'
  replace: 'driverVersion: "{driverVersion}"'
- file: helm/values.yaml
  regexp: 'installerImage: .*'
  replace: 'installerImage: com.sap.ai/nvidia-installer-{kernelVersion}-{driverVersion}'

dependencies:
- component: system-services/gardenlinux-dev
  patch:
  - file: Dockerfile
    regexp: FROM \S* AS builder
    replace: FROM {docker_registry}{imageName}:{builtin.version} AS builder
  - file: Dockerfile
    regexp: ARG KERNEL_VERSION=.*
    replace: 'ARG KERNEL_VERSION={kernelVersion}'
  - file: helm/values.yaml
    regexp: 'gardenlinuxVersion: .*'
    replace: 'gardenlinuxVersion: {gardenlinuxVersion}'
  - file: helm/values.yaml
    regexp: 'values: \[\".*\"\]'
    replace: 'values: ["{gardenlinuxVersion}"]'
  - file: helm/values.yaml
    regexp: 'kernelVersion: .*'
    replace: 'kernelVersion: "{kernelVersion}"'
