version: 1.2.0-sap5
description: system pod for installing nvidia gpu drivers in the host operating system

steps:
  jenkins:
    type: jenkinsJob
    job: aicore/nvidia-installer
    params:
      ComponentName: nvidia-installer
      BuildContext: '{builtin.encoded_contexts}'
      RunStaticScans: '{RunStaticScans}'
      RunUnitTests: '{RunUnitTests}'
      Release: '{Release}'
      Build: '{Build}'
      BuildXmake: '{BuildXmake}'
      TREEISH: '{builtin.git_commit}'
      RunTests: '{RunTests}'
      RunCheckmarx: '{RunCheckmarx}'
      RunWhitesource: '{RunWhitesource}'
      RunSonarQube: '{RunSonarQube}'
      RunWhitesourceDocker: '{RunWhitesourceDocker}'
      RunPPMSComplianceForImage: '{RunPPMSComplianceForImage}'
  build:
    type: dockerbuild
    artifact: image
    dockerfile: Dockerfile
    buildArgs:
      GIT_COMMIT: '{builtin.git_commit}'
      GIT_TAG: '{builtin.version}'
      GIT_TREE_STATE: '{builtin.git_tree_state}'
  whitesource:
    type: whitesource

artifacts:
  image:
    type: docker
    imageName: com.sap.ai/nvidia-installer{image_suffix}

context:
  imageName: com.sap.ai/nvidia-installer{image_suffix}

pipelines:
  local:
    build: build
  push-validation:
    build: jenkins
  main:
    build: jenkins
  release:
    build: jenkins

patch:
- file: .xmake.cfg
  regexp: version=.*
  replace: version={builtin.version}
- file: helm/Chart.yaml
  yaml_path: version
  replace: '{builtin.version}'

