version: 1.1.4
description: system pod for installing nvidia gpu drivers in the host operating system

steps:
  jenkins:
    type: jenkinsJob
    job: aicore/system-services-helm
    params:
      ComponentName: nvidia-installer
      BuildContext: '{builtin.encoded_contexts}'
      RunStaticScans: '{RunStaticScans}'
      RunUnitTests: '{RunUnitTests}'
      RunTests: '{RunTests}'
      RunCheckmarx: '{RunCheckmarx}'
      RunWhitesource: '{RunWhitesource}'
      RunSonarQube: '{RunSonarQube}'
      Release: '{Release}'
      Build: '{Build}'
      BuildXmake: '{BuildXmake}'
      TREEISH: '{builtin.git_commit}'
  build:
    type: dockerbuild
    imageName: '{imageName}'
    registry: '{docker_registry}'
  tagRelease:
    type: tagRelease

context:
  imageName: com.sap.ai/nvidia-installer{image_suffix}

pipelines:
  local:
    build: build
  push-validation:
    build: jenkins
  master:
    build: jenkins
  release:
    build: jenkins

patch:
- file: .xmake.cfg
  regexp: version=.*
  replace: version={builtin.version}
- file: helm/Chart.yaml
  yaml_path: version
  replace: '{builtin.version}'

