{{- if .Values.nvidiaDevicePlugin.gpuConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nvidia-device-plugin.gpuConfig.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "nvidia-device-plugin.name" . }}
data:
  gpu_config.json: |
{{ .Values.nvidiaDevicePlugin.gpuConfig | toJson | indent 4 }}
{{- end }}
