apiVersion: v1
kind: Secret
metadata:
  name: {{ template "image-pull-secret" . }}
  annotations:
{{ toYaml .Values.global.imagePullSecret.annotations | indent 4 }}
data:
  .dockercfg: "{{ .Values.global.imagePullSecret.dockercfg }}"
type: kubernetes.io/dockercfg

---
