{{- if .Values.imagePullSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "image-pull-secret" . }}
  annotations:
{{ toYaml .Values.imagePullSecret.annotations | indent 4 }}
data:
  .dockercfg: "{{ .Values.imagePullSecret.dockercfg }}"
type: kubernetes.io/dockercfg
{{- end }}

---
