apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service-account" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "service-account" . }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "service-account" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "service-account" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "service-account" . }}
  apiGroup: rbac.authorization.k8s.io
