dockerRegistry:
  overwrite: false

allowCompilation: false
forceCompile: false
debug: false
driverBucketSecret: nvidia-driver-bucket-read
gardenlinuxVersion: 184.0.0

imagePullSecrets:
# - name: hello
# - name: bla

nvidiaInstaller:
  driverVersion: "450.80.02"
  hostDriverPath: /opt/drivers
  # We use a combination of nodeAffinity and nodeSelector
  # nodeAffinity is used for all GPU nodes, and may be overridden in mlf-deploy (e.g. to support pools of different GPU types)
  # nodeSelector is used per-OS to select which OS-specific installation method is used
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gpu
          operator: Exists
        # - key: gpu
        #   operator: In
        #   values:
        #   - nvidia-tesla-t4
        #   - nvidia-tesla-v100
        #   - nvidia-tesla-k80
        - key: os-version
          operator: In
          values:
          - 184.0.0
  tolerations:
   - key: "nvidia.com/gpu"
     operator: "Exists"
     effect: "NoSchedule"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 50m
      memory: 10Mi

gardenlinuxNvidiaInstaller:
  devImage: com.sap.ai/gardenlinux-dev
  # devTag: 184.0.0
  installerImage: com.sap.ai/nvidia-installer
  # installerTag: 1.1.4
  # nodeSelector: {"os": "gardenlinux"}
  environment:
   - name: IGNORE_MISSING_MODULE_SYMVERS
     value: "1"

nvidiaDevicePlugin:
  image: k8s.gcr.io/nvidia-gpu-device-plugin@sha256
  tag: 08509a36233c5096bb273a492251a9a5ca28558ab36d74007ca2a9d3f0b61e1d
  pauseImage: k8s.gcr.io/pause-amd64
  pauseTag: 3.1
  hostDevicePluginPath: /var/lib/kubelet/device-plugins
  nodeSelector: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gpu
          operator: Exists
  tolerations:
   - key: CriticalAddonsOnly
     operator: Exists
   - key: "nvidia.com/gpu"
     operator: "Exists"
     effect: "NoSchedule"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
    limits:
      cpu: 50m
      memory: 10Mi
