FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.26.1 AS builder
ARG TARGETOS
ARG TARGETARCH

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get --no-install-suggests --no-install-recommends -o Dpkg::Options::="--force-confnew" --allow-downgrades --allow-remove-essential \
    --allow-change-held-packages -fuy install \
    \
    ca-certificates \
    curl \
    lsb-release \
    \
    && \
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    printf "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \
    apt-get install vault && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /cdup
COPY go.mod go.mod
COPY go.sum go.sum
COPY main.go main.go
COPY oci.go oci.go
COPY ocm.go ocm.go
COPY vault.go vault.go
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -a -o cdup github.com/gardenlinux/gardenlinux-nvidia-installer/cdup

FROM docker.io/library/debian:forky-20260316-slim
WORKDIR /
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get --no-install-suggests --no-install-recommends -o Dpkg::Options::="--force-confnew" --allow-downgrades --allow-remove-essential \
    --allow-change-held-packages -fuy install \
    \
    ca-certificates \
    curl \
    jq \
    \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/bin/vault /usr/bin/vault

ENTRYPOINT ["/cdup"]
COPY --from=builder /cdup/cdup .

USER 65532:65532
