
apiVersion: v1
kind: Pod
metadata:
  name: gpu-debug
  namespace: default
spec:
  containers:
    - name: gpu-debug-pod
      image: debian
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
      command: ["/bin/bash"]
      args: ['-c', "ls -l /dev/nvidia* ; sleep 10000d"]
  nodeSelector:
    nvidia-driver: image
  tolerations:
   - key: "nvidia.com/gpu"
     operator: "Exists"
     effect: "NoSchedule"
   - key: "test"
     operator: "Exists"
     effect: "NoSchedule"
