name: cdup
on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'Version/Tag to checkout'
        required: true
        type: string
      commit_input:
        description: 'Commit of the Tag'
        required: true
        type: string

jobs:
  cdup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_input }}

      - name: Build cdup
        run: |
          cd cdup
          go build -o cdup
      - name: Run cdup
        run: |
          ./cdup/cdup -v ${{ github.event.inputs.version_input }} -c ${{ github.event.inputs.commit_input }}