name: cdup
on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'Version/Tag to checkout'
        required: true
        type: string
      commit_input:
        description: 'Commit of the Tag'
        required: true
        type: string

jobs:
  cdup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_input }}
      - name: Authenticate to Vault via GitHub OIDC
        uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
        with:
          method: jwt
          url: ${{ vars.VAULT_ADDR }}
          namespace: ${{ vars.VAULT_NAMESPACE }}
          path: ${{ vars.VAULT_PATH }}
          role: ${{ vars.VAULT_ROLE }}
          exportToken: true
      - name: Build cdup
        run: |
          cd cdup
          go build -o cdup
      - name: Run cdup
        run: |
          ./cdup/cdup -v ${{ github.event.inputs.version_input }} -c ${{ github.event.inputs.commit_input }}
