name: Create GitHub release

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
    # Create a GitHub release when a PR is merged that changes the release-version.yaml file
      - 'release-version.yaml'

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  create-release:
    if: github.event.pull_request.merged == true # Only run if the PR was merged - needed to avoid creating a release for every PR that is closed without merging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          release_tag=$(cat release-version.yaml)
          
          MAJOR=$(echo "$release_tag" | cut -d. -f1)
          MINOR=$(echo "$release_tag" | cut -d. -f2)
          PATCH=$(echo "$release_tag" | cut -d. -f3)
          
          # Create the release with the new tag and generate release notes based on the commits since the last release
          gh release create "${release_tag}" \
            --title "${release_tag}" \
            --generate-notes
          
          # Merge main into the <major>.<minor> branch to update the release branch with the latest changes from main
          release_branch="${MAJOR}.${MINOR}"
          git checkout -B "${release_branch}" origin/"${release_branch}" || git checkout -b "${release_branch}"
          git merge main --no-edit
          git push origin "${release_branch}"
          
          # Merge main into the <major> branch to update the release branch with the latest changes from main
          release_branch="${MAJOR}"
          git checkout -B "${release_branch}" origin/"${release_branch}" || git checkout -b "${release_branch}"
          git merge main --no-edit
          git push origin "${release_branch}"
