name: Release
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build-driver:
    uses: ./.github/workflows/build_driver.yml

  build-image:
    needs: build-driver
    uses: ./.github/workflows/build_image.yml
