name: Update Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Pip packages
        run: pip install html2text pyyaml requests

      - name: Update Version
        id: update-version
        run: |
          OUTPUT=$(python ./.ci/update_versions.py)

          # Parse the output for each update type
          GARDENLINUX_VERSION_UPDATE=$(echo "$OUTPUT" | grep "GARDENLINUX_VERSION_UPDATE" | cut -d'=' -f2)
          NVIDIA_DRIVER_VERSION_UPDATE=$(echo "$OUTPUT" | grep "NVIDIA_DRIVER_VERSION_UPDATE" | cut -d'=' -f2)
          GVISOR_VERSION_UPDATE=$(echo "$OUTPUT" | grep "GVISOR_VERSION_UPDATE" | cut -d'=' -f2)

          echo "has_update=$([[ $GARDENLINUX_VERSION_UPDATE == 'true' || $NVIDIA_DRIVER_VERSION_UPDATE == 'true' || $GVISOR_VERSION_UPDATE == 'true' ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Update History
        id: update-history
        if: ${{ steps.update-version.outputs.has_update == 'true' }}
        run: |
          python ./.ci/update_history.py

      - name: Add versions commit to release branch
        if: ${{ steps.update-version.outputs.has_update == 'true' }}
        run: |
          source .ci/git_ops.sh
          configure_git_identity "Garden Linux Builder" "gardenlinux@users.noreply.github.com"
          git checkout -b update-version
          commit_and_push_branch "update-version" versions.yaml history.yaml
          create_pr "update-version" main "Update versions" "automated update"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

