name: Update Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get release branch and tag 
        id: get-release-branch-tag
        run: |
          # Get the latest release branch, based on the latest release tag
          TAG=$(gh release list --repo "${{ github.repository }}" --json tagName \
              --jq '[.[] | select(.tagName | test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))] | first | .tagName')
          MAJOR_VERSION=$(echo "$TAG" | cut -d'.' -f1)
          RELEASE_BRANCH="releases/${MAJOR_VERSION}.x.x"
          echo "release_branch=${RELEASE_BRANCH}" >> $GITHUB_OUTPUT
          echo "release_tag=${TAG}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.get-release-branch-tag.outputs.release_branch }}

      - name: Install Pip packages
        run: pip install html2text pyyaml

      - name: Update Version
        id: update-version
        run: |
          OUTPUT=$(python ./.ci/update_versions.py)
          
          # Parse the output for each update type
          GARDENLINUX_VERSION_UPDATE=$(echo "$OUTPUT" | grep "GARDENLINUX_VERSION_UPDATE" | cut -d'=' -f2)
          NVIDIA_DRIVER_VERSION_UPDATE=$(echo "$OUTPUT" | grep "NVIDIA_DRIVER_VERSION_UPDATE" | cut -d'=' -f2)
          
          echo "gardenlinux-update=$GARDENLINUX_VERSION_UPDATE" >> $GITHUB_OUTPUT
          echo "nvidia-update=$NVIDIA_DRIVER_VERSION_UPDATE" >> $GITHUB_OUTPUT
          echo "has-update=$([[ $GARDENLINUX_VERSION_UPDATE == 'true' || $NVIDIA_DRIVER_VERSION_UPDATE == 'true' ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Add versions commit to release branch
        run: |
          if [[ '${{ steps.update-version.outputs.has-update }}' ]]; then
            git add versions.yaml
            git config --global user.name "Garden Linux Builder"
            git config --global user.email "gardenlinux@users.noreply.github.com"
            git commit -am 'Update Garden Linux versions'
            echo "version_commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT 
            git push
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cherry-pick versions commit to main
        run: |
          if [[ '${{ steps.update-version.outputs.has-update }}' ]]; then
            git checkout origin/main
            git config --global user.name "Garden Linux Builder"
            git config --global user.email "gardenlinux@users.noreply.github.com"
            git cherry-pick ${{ steps.update-version.outputs.version_commit }}
            git push --set-upstream origin update-version
            UPDATE_PR_LINK=$(gh pr create --base main --head update-version --title 'Update Garden Linux versions' --body "automated update")
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Patch release for Garden Linux version update
        if: steps.update-version.outputs.gardenlinux-update == 'true'
        run: |
          echo "Garden Linux was updated!"
          TAG=${{ steps.get-release-branch-tag.outputs.release_tag }}
          
          MAJOR=$(echo $TAG | cut -d. -f1)
          MINOR=$(echo $TAG | cut -d. -f2)
          PATCH=$(echo $TAG | cut -d. -f3)
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          RELEASE_TAG="${MAJOR}.${MINOR}.${NEW_PATCH}"
          # Create the release if it does not yet exist; ignore error if it already does.
          gh release create "${RELEASE_TAG}" \
            --title "${RELEASE_TAG}" \

      - name: Create Minor version release for NVIDIA driver update
        if: steps.update-version.outputs.nvidia-update == 'true'
        run: |
          echo "NVIDIA driver was updated!"
          TAG=${{ steps.get-release-branch-tag.outputs.release_tag }}
          
          MAJOR=$(echo $TAG | cut -d. -f1)
          MINOR=$(echo $TAG | cut -d. -f2)
          PATCH=$(echo $TAG | cut -d. -f3)
          # Increment patch version
          NEW_MINOR=$((MINOR + 1))
          RELEASE_TAG="${MAJOR}.${NEW_MINOR}.0"
          # Create the release if it does not yet exist; ignore error if it already does.
          gh release create "${RELEASE_TAG}" \
            --title "${RELEASE_TAG}" \

  build-images:
    needs: update-version
    uses: ./.github/workflows/build_image.yml

