name: Update Versions

on:
  workflow_dispatch:
    inputs:
      gl_version:
        description: "GL version"
        default: "no_update"
        required: true

  schedule:
    - cron: '0 0 * * *'
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pip packages
        run: pip install html2text pyyaml

      - name: Update Version
        id: update-version
        run: |
          OUTPUT=$(python ./.ci/update_versions.py "${{ github.event.inputs.gl_version }}")
          echo "has-update<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: create pull request
        run: |
          if [[ '${{ steps.update-version.outputs.has-update }}' ]]; then
            git checkout -b update-version
            git add versions.yaml
            git config --global user.name "Garden Linux Builder"
            git config --global user.email "gardenlinux@users.noreply.github.com"
            git commit -am 'Update Version'
            git pull --rebase origin update-version || true
            git push --set-upstream origin update-version
            UPDATE_PR_LINK=$(gh pr create --base main --head update-version --title 'Update version' --body "automated update")
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
